--Creating a table

CREATE TABLE Player(
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AGE INTEGER NOT NULL,
    NATIONALITY VARCHAR(100) NOT NULL,
    DOB TIMESTAMP,
    DESIGNATION INTEGER,
    PRIMARY KEY(ID)
);